files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%two_letters_code%/%original_file_name%
    translate_attributes: 0
    update_option: update_as_unapproved
  - source: /app/src/main/res/values/arrays.xml
    translation: /app/src/main/res/values-%two_letters_code%/%original_file_name%
    update_option: update_as_unapproved
  - source: /app/src/main/play/release-notes/en-US/*
    translation: /app/src/main/play/release-notes/%locale%/%original_file_name%
    update_option: update_as_unapproved
  - source: /app/src/main/play/listings/en-US/*
    translation: /app/src/main/play/listings/%locale%/%original_file_name%
    update_option: update_as_unapproved
